#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#solved 12/31/17, approx time 12 mins

def main():
	#Fibonacci variables. A is first, B is second. During the loop their places will both increment by one - after one loop, they will be 2 and 3.
	fibnumberA = 1
	fibnumberB = 2
	#evenFibTotal starts at 2, we will add after incrementing fibB
	evenFibTotal = 2

	#variable to stop at specific upper limit
	maxFib = 4000000
	while fibnumberB < maxFib:
		tempFib = fibnumberB + fibnumberA
		print tempFib
		fibnumberA = fibnumberB
		fibnumberB = tempFib
		if fibnumberB%2 == 0:
			evenFibTotal = evenFibTotal + fibnumberB

	print "Even Fib total is " 
	print evenFibTotal

main()



